# Generated by Django 3.1.3 on 2020-11-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sex',
        ),
    ]
