# Generated by Django 3.1.3 on 2020-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
