# Generated by Django 3.1.3 on 2020-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
